### ISSUE TITLE
Microservice spec doesn't accept upd port specification

### ISSUE THREAD

**Issue by franckOL** [eclipse-iofog/Controller#724]
From dockerfile spec:
```
EXPOSE 8285/udp
```
and for the CLI
```
sudo docker run -p 53160:53160/udp....
```

**Comment by Pixcell** [comment]
Thank you for reporting this. The feature request has been accepted, we'll look into it and keep you posted.

**Comment by Pixcell** [comment]
Resolved by:

Controller: https://github.com/eclipse-iofog/Controller/pull/726
Agent: https://github.com/eclipse-iofog/Agent/pull/368

To expose a port using UDP protocol, set the `protocol` field of the port mapping to `udp` in the YAML file describing the microservice container

```
          ports:
            - external: 5001
              internal: 80
            - external: 5002
              internal: 81
              protocol: udp
 ```
